apiVersion: v1
kind: Pod
metadata:
  name: cpu-perf-03
spec:
  containers:
  - image: typeoneg/stresstest-pod:v1 
    name: cpu-perf
    command: [ "sh", "-c", "sleep infinity" ]
  nodeSelector:
    #kubernetes.io/os: linux
    #agentpool: usrnp01
    kubernetes.io/hostname: aks-usrnp-27798712-vmss000002 
