## Generic VMS RG
CLUSTER_NAME="cka"
CLUSTER_RG_NAME="rg-vms-$CLUSTER_NAME"
CLUSTER_RG_LOCATION="westeurope"
CLUSTER_VNET_PREFIX_CIDR="10.7"

CLUSTER_HOW_MANY_CCP_NODES="1"
CLUSTER_HOW_MANY_WORKER_NODES="3"

CLUSTER_LOAD_BALANCER_NGINX="1"

## Cluster Network
CLUSTER_VNET_NAME="vnet-$CLUSTER_NAME"
CLUSTER_VNET_CIDR="$CLUSTER_VNET_PREFIX_CIDR.0.0/16"
CLUSTER_VNET_SNET_NAME="snet-$CLUSTER_NAME"
CLUSTER_VNET_SNET_CIDR="$CLUSTER_VNET_PREFIX_CIDR.0.0/23"



## Control Plane - VM Specs
CCP_AUTH_TYPE="ssh"
CCP_NAME="ccp"
CCP_INTERNAL_NAME="ccp"
CCP_IMAGE_PROVIDER="Canonical"
CCP_IMAGE_OFFER="0001-com-ubuntu-server-focal"
CCP_IMAGE_SKU="20_04-lts-gen2"
CCP_IMAGE_VERSION="latest"
CCP_IMAGE="$CCP_IMAGE_PROVIDER:$CCP_IMAGE_OFFER:$CCP_IMAGE_SKU:$CCP_IMAGE_VERSION"
CCP_SIZE="Standard_D4s_v3"
CCP_STORAGE_SKU="Standard_LRS"
CCP_OS_DISK_SIZE="70"
CCP_TAGS="purpose=ccp-server"



## Worker Node - VM Specs
WN_AUTH_TYPE="ssh"
WN_NAME="wknode"
WN_INTERNAL_NAME="wknode"
WN_IMAGE_PROVIDER="Canonical"
WN_IMAGE_OFFER="0001-com-ubuntu-server-focal"
WN_IMAGE_SKU="20_04-lts-gen2"
WN_IMAGE_VERSION="latest"
WN_IMAGE="$WN_IMAGE_PROVIDER:$WN_IMAGE_OFFER:$WN_IMAGE_SKU:$WN_IMAGE_VERSION"
WN_SIZE="Standard_D4s_v3"
WN_STORAGE_SKU="Standard_LRS"
WN_OS_DISK_SIZE="80"
WN_TAGS="purpose=wknode-server"


## Load Balancer Nginx - VM Specs
LB_AUTH_TYPE="ssh"
LB_NAME="lb01"
LB_INTERNAL_NAME="lb01"
LB_IMAGE_PROVIDER="Canonical"
LB_IMAGE_OFFER="0001-com-ubuntu-server-focal"
LB_IMAGE_SKU="20_04-lts-gen2"
LB_IMAGE_VERSION="latest"
LB_IMAGE="$LB_IMAGE_PROVIDER:$LB_IMAGE_OFFER:$LB_IMAGE_SKU:$LB_IMAGE_VERSION"
LB_SIZE="Standard_D2s_v3"
LB_STORAGE_SKU="Standard_LRS"
LB_OS_DISK_SIZE="80"
LB_TAGS="purpose=lb-server"
