## ML CORE Settings
ML_PURPOSE="aks-potencias"

# Accepted values are "FastProd" and "DevTest"
ML_AKS_PURPOSE="DevTest"

#  Default: Standard_D3_v2.
ML_AKS_VM_SIZE="Standard_D3_v2"

# If We Use FastProd Then below number >= 3
ML_AKS_NODE_COUNT="1"
ML_RG_LOCATION="westeurope"

## ML Settings
ML_RG_NAME="rg-"$ML_PURPOSE
ML_WORK_SPACE_NAME="ml-wk-"$ML_PURPOSE

## AKS
AKS_NAME=$ML_PURPOSE
AKS_NODE_COUNT=$ML_AKS_NODE_COUNT

# Accepted values are "PublicIp" and "InternalLoadBalancer". Default is "PublicIp".
AKS_LB_TYPE="PublicIp"
AKS_RG_LOCATION=$ML_RG_LOCATION
AKS_ML_PURPOSE=$ML_AKS_PURPOSE
AKS_ML_VM_SIZE=$ML_AKS_VM_SIZE

## AKS NETWORK
AKS_VNET_RG_NAME=$ML_RG_NAME
AKS_VNET_NAME="vnet-"$ML_PURPOSE
AKS_VNET_ADDRESS_PREFIX="10.0.0.0/16"
AKS_VNET_SUBNET_NAME="sn-"$ML_PURPOSE
AKS_VNET_SUBNET_PREFIX="10.0.0.0/22"
AKS_DNS_SERVICE_IP="10.0.4.10"
AKS_DOCKER_BRIDGE_IP="172.17.0.1/16"
AKS_SERVICE_CIDR="10.0.4.0/23"

## VM Settings
VM_SUBNET_NAME="ssh-client"
VM_SNET_CIDR="10.0.6.0/28"
VM_PRIV_IP="10.0.6.4/32"
MY_HOME_PUBLIC_IP=$(curl ifconfig.io)

## Public IP name
VM_PUBLIC_IP_NAME="sshclientpublicip"
VM_DEFAULT_IP_CONFIG="ipconfig1"

## VM SSH Client
VM_RG_LOCATION=$ML_RG_LOCATION
VM_AUTH_TYPE="ssh"
VM_NAME="sshclient-"$ML_PURPOSE
VM_INTERNAL_NAME="sshclient-"$ML_PURPOSE
VM_IMAGE_PROVIDER="Canonical"
VM_IMAGE_OFFER="UbuntuServer"
VM_IMAGE_SKU="18.04-LTS"
VM_IMAGE_VERSION="latest"
VM_IMAGE="$VM_IMAGE_PROVIDER:$VM_IMAGE_OFFER:$VM_IMAGE_SKU:$VM_IMAGE_VERSION"
VM_PUBLIC_IP=""
VM_VNET_NAME=$AKS_VNET_NAME
VM_SIZE="Standard_D2s_v3"
VM_STORAGE_SKU="Standard_LRS"
VM_OS_DISK_SIZE="40"
VM_OS_DISK_NAME="$VM_NAME""_disk_01"
VM_NSG_NAME="$VM_NAME""_nsg"
VM_NIC_NAME="$VM_NAME""nic01"
VM_TAGS="env=ml"
