## AKS Settings
AKS_PURPOSE="agic"
AKS_RG_NAME="rg-aks-"$AKS_PURPOSE
AKS_LOCATION="westus"

## AKS Vnet
AKS_MAIN_VNET_NAME="main-vnet"
AKS_ADDRESS_PREFIX="10.0.0.0/16"
AKS_SUBNET_NAME="aks-subnet"
AKS_SUBNET_PREFIX="10.0.8.0/21"

APPGTW_SUBNET_CIDR="10.0.24.0/24"
APPGTW_NAME="ninjascroll"

## Aks Cluster Settings
AKS_PURPOSE=$AKS_PURPOSE
AKS_RG_NAME=$AKS_RG_NAME
AKS_RG_LOCATION=$AKS_LOCATION
AKS_CLUSTER_NAME="aks-"$AKS_PURPOSE
AKS_NODE_SIZE="Standard_DS2_v2"
AKS_NODE_COUNT="3"
AKS_NODE_DISK_SIZE="60"
AKS_VMSETTYPE="VirtualMachineScaleSets"
AKS_VERSION="1.19.9"
AKS_CNI_PLUGIN="azure"
AKS_CLUSTER_SRV_CIDR="10.0.32.0/21"
AKS_CLUSTER_DNS="10.0.32.10"
AKS_CLUSTER_DOCKER_BRIDGE="172.17.0.1/16"

## Generic Network Settings
MY_HOME_PUBLIC_IP=$(curl ifconfig.io)

## VM SSH Network Settings
SSH_VM_SUBNET_NAME="sshclient-subnet"
SSH_VM_SUBNET_CIDR="10.0.16.0/28"
SSH_VM_SUBNET_PRIV_IP="10.0.16.4/32"

## VM SSH Client
SSH_VM_RG_LOCATION=$AKS_LOCATION
SSH_VM_AUTH_TYPE="ssh"
SSH_VM_NAME="sshclient-"$AKS_PURPOSE
SSH_VM_INTERNAL_NAME="sshclient-"$AKS_PURPOSE
SSH_VM_IMAGE_PROVIDER="Canonical"
SSH_VM_IMAGE_OFFER="UbuntuServer"
SSH_VM_IMAGE_SKU="18.04-LTS"
SSH_VM_IMAGE_VERSION="latest"
SSH_VM_IMAGE="$SSH_VM_IMAGE_PROVIDER:$SSH_VM_IMAGE_OFFER:$SSH_VM_IMAGE_SKU:$SSH_VM_IMAGE_VERSION"
SSH_VM_PUBLIC_IP=""
SSH_VM_VNET_NAME=$AKS_MAIN_VNET_NAME
SSH_VM_VNET_SUBNET_NAME="ssh-client"
SSH_VM_SIZE="Standard_D2s_v3"
SSH_VM_STORAGE_SKU="Standard_LRS"
SSH_VM_OS_DISK_SIZE="40"
SSH_VM_OS_DISK_NAME="$SSH_VM_NAME""_disk_01"
SSH_VM_NSG_NAME="$SSH_VM_NAME""_nsg"
SSH_VM_NIC_NAME="$SSH_VM_NAME""nic01"
SSH_VM_TAGS="env=kubernetes"
SSH_VM_PUBLIC_IP_NAME="sshclientpublicip"
SSH_VM_DEFAULT_IP_CONFIG="ipconfig1"

