apiVersion: v1
kind: ConfigMap
metadata:
  name: index-html-configmap
  namespace: default
data:
  index.html: |
    <!DOCTYPE html>
    <html>
      <body>
        <title><!--# echo var="server_addr" default="unknown_host" -->:<!--# echo var="server_port" default="unknown_port" -->:<!--# echo var="hostname" default="unknown_host" --></title>
      </body>
    </html>
