apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
spec:
  containers:
  - name: c-01
    image: nginx
    ports:
    - containerPort: 80  
  - name: c-02
    image: alpine
    command: ["watch", "wget", "-qO-", "localhost"]
  nodeSelector:
    kubernetes.io/os: linux
    #kubernetes.io/hostname:
    agentpool: usrnp
