apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azure-managed-disk
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: managed-premium
  volumeName: pvc-266234f4-0c72-4d3f-ac68-c0492322199b 
  resources:
    requests:
      storage: 5Gi




# Retain Policy
# kubectl patch pv <your-pv-name> -p '{"spec":{"persistentVolumeReclaimPolicy":"Retain"}}'

# Change Status Released to Available
# kubectl patch pv pvc-266234f4-0c72-4d3f-ac68-c0492322199b -p {"spec":{"claimRef":null}}



#accessModes

#ReadWriteOnce
# the volume can be mounted as read-write by a single node. ReadWriteOnce access mode still can allow multiple pods to access the volume when the pods are running on the same node.

#ReadOnlyMany
# the volume can be mounted as read-only by many nodes.

#ReadWriteMany
# the volume can be mounted as read-write by many nodes.

#ReadWriteOnce
# the volume can be mounted as read-write by a single Pod. 
# Use ReadWriteOncePod access mode if you want to ensure that only one pod across whole cluster can read that PVC or write to it. 
# This is only supported for CSI volumes and Kubernetes version 1.22+.
