kind: Pod
apiVersion: v1
metadata:
  name: mp3
spec:
  containers:
  - name: mp3
    image: nginx:latest
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 250m
        memory: 256Mi
    volumeMounts:
    - mountPath: "/mnt/azure"
      name: volume
  nodeSelector:
    kubernetes.io/os: linux
  volumes:
    - name: volume
      persistentVolumeClaim:
        claimName: azure-managed-disk
