## AKS Settings more prone to be changed
AKS_PURPOSE="knet01"
AKS_LOCATION="eastus"
AKS_VERSION="1.23.5"


## AKS Main definitions
AKS_HAS_AZURE_MONITOR="0"
AKS_HAS_AUTO_SCALER="0"
AKS_HAS_MANAGED_IDENTITY="1"
AKS_HAS_NETWORK_POLICY="0"
AKS_HAS_2ND_NP="0"


## AKS NP Settings
AKS_RG_NAME="rg-aks-"$PURPOSE
AKS_CLUSTER_NAME="aks-"$PURPOSE
AKS_SYSNP_NODE_SIZE="Standard_D4s_v3"
AKS_USRNP_NODE_SIZE="Standard_D4s_v3"
AKS_SYSNP_COUNT="1"
AKS_USRNP_COUNT="3"
AKS_SYSNP_DISK_SIZE="90"
AKS_USRNP_DISK_SIZE="100"
AKS_NP_VMSS_SET_TYPE="VirtualMachineScaleSets"   # Or "AvailabilitySet"

## AKS Networking
AKS_VNET_RG=$RG_NAME
AKS_NETWORK_PLUGIN="kubenet"
AKS_VNET_NAME="vnet-"$CLUSTER_NAME
AKS_VNET_CIDR="10.10.0.0/16"
AKS_VNET_SNET_NAME="snet-"$PURPOSE
AKS_VNET_SNET_CIDR="10.240.0.0/16"
AKS_POD_CIDR="10.244.0.0/16"
AKS_CLUSTER_SRV_CIDR="10.0.0.0/16"
AKS_CLUSTER_DNS="10.0.0.10"
AKS_CLUSTER_DOCKER_BRIDGE="172.17.0.1/16"



MY_HOME_PUBLIC_IP=$(curl ifconfig.io)

