## AKS Settings more prone to be changed
AKS_PURPOSE="lab03"
AKS_LOCATION="westeurope"
AKS_VERSION="1.21.9"


## AKS Main definitions
AKS_HAS_AZURE_MONITOR="1"
AKS_HAS_AUTO_SCALER="1"
AKS_HAS_MANAGED_IDENTITY="1"
AKS_HAS_2ND_NP="1"


## AKS NP Settings
AKS_RG_NAME="rg-aks-"$AKS_PURPOSE
AKS_CLUSTER_NAME="aks-"$AKS_PURPOSE
AKS_SYSNP_NODE_SIZE="Standard_D4s_v3"
AKS_USRNP_NODE_SIZE="Standard_D4s_v3"
AKS_SYSNP_COUNT="1"
AKS_USRNP_COUNT="3"
AKS_SYSNP_DISK_SIZE="90"
AKS_USRNP_DISK_SIZE="100"
AKS_NP_VM_SET_TYPE="VirtualMachineScaleSets"   # Or "AvailabilitySet"


## AKS Networking
AKS_VNET_RG=$AKS_RG_NAME
AKS_NETWORK_PLUGIN="kubenet"
AKS_VNET_NAME="vnet-"$AKS_CLUSTER_NAME
AKS_VNET_CIDR="10.10.0.0/16"
AKS_VNET_SNET_NAME="snet-"$AKS_CLUSTER_NAME
AKS_VNET_SNET_CIDR="10.10.0.0/24"
AKS_POD_CIDR="10.240.0.0/16"
AKS_CLUSTER_SRV_CIDR="10.0.0.0/16"
AKS_CLUSTER_DNS="10.0.0.10"
AKS_CLUSTER_DOCKER_BRIDGE="172.17.0.1/16"


## BYO ISP PIP
MY_HOME_PUBLIC_IP=$(curl -s -4 ifconfig.io)

