## Running Options
CREATE_MAIL_SRV="1"
CREATE_POSTFIX="0"

## Core Networking
AKS_MAIN_VNET_RG="rg-aks-cal"
AKS_MAIN_VNET_NAME="vnet-full-aks-cal"
AKS_MAIN_VNET_LOCATION="eastus"
AKS_MAIN_VNET_CIDR="10.0.0.0/16"
AKS_SUBNET_CIDR="10.0.0.0/22"

## VM Specific Networking
VM_MAIL_SUBNET_NAME="mail-server"
VM_MAIL_SNET_CIDR="10.0.10.0/28"
VM_MAIL_PRIV_IP="10.0.10.4/32"

## Local ISP PIP
VM_MY_ISP_IP=$(curl ifconfig.io)

## Public IP Name
VM_MAIL_PUBLIC_IP_NAME="mailsrvpip"
VM_MAIL_DEFAULT_IP_CONFIG="ipconfig1"

## VM SSH Client
VM_MAIL_RG_LOCATION=$AKS_MAIN_VNET_LOCATION
VM_MAIL_AUTH_TYPE="ssh"
VM_MAIL_NAME="mail-srv"
VM_MAIL_INTERNAL_NAME="mail-srv"
VM_MAIL_IMAGE_PROVIDER="Canonical"
VM_MAIL_IMAGE_OFFER="0001-com-ubuntu-server-focal"
VM_MAIL_IMAGE_SKU="20_04-lts-gen2"
VM_MAIL_IMAGE_VERSION="latest"
VM_MAIL_IMAGE="$VM_MAIL_IMAGE_PROVIDER:$VM_MAIL_IMAGE_OFFER:$VM_MAIL_IMAGE_SKU:$VM_MAIL_IMAGE_VERSION"
VM_MAIL_PUBLIC_IP="" 
VM_MAIL_SIZE="Standard_D2s_v3"
VM_MAIL_STORAGE_SKU="Standard_LRS"
VM_MAIL_OS_DISK_SIZE="40"
VM_MAIL_OS_DISK_NAME="$VM_MAIL_NAME""_disk_01"
VM_MAIL_NSG_NAME="$VM_MAIL_NAME""_nsg"
VM_MAIL_NIC_NAME="$VM_MAIL_NAME""nic01"
VM_MAIL_TAGS="purpose=mail-server"

