## AKS
HAS_AZURE_MONITOR="0"
PURPOSE="lab"
LOCATION="westeurope"
RG_NAME="rg-aks-"$PURPOSE
CLUSTER_NAME="aks-"$PURPOSE
NODE_SIZE="Standard_D4s_v3"
#NODE_SIZE="Standard_DS2_v2"
NODE_COUNT="2"
NODE_DISK_SIZE="45"
VMSETTYPE="VirtualMachineScaleSets"
VERSION="1.18.14"

## AKS SSH Keys
ADMIN_USERNAME="gits"

## Networking
VNET_RG=$RG_NAME
CNI_PLUGIN="azure"
AKS_VNET="vnet-full-"$CLUSTER_NAME
AKS_VNET_RG="rg-vnet-full-"$CLUSTER_NAME
AKS_VNET_CIDR="10.0.0.0/16"
AKS_SNET="snet-full-"$PURPOSE
AKS_SNET_CIDR="10.0.0.0/22"

AKS_CLUSTER_SRV_CIDR="10.0.4.0/23"
AKS_CLUSTER_DNS="10.0.4.10"
AKS_CLUSTER_DOCKER_BRIDGE="172.17.0.1/16"

VM_SUBNET_NAME="ssh-client"
VM_SNET_CIDR="10.0.6.0/28"
VM_PRIV_IP="10.0.6.4/32"

MY_HOME_PUBLIC_IP=$(curl ifconfig.io)

WIN_VM_SUBNET_NAME="rdc-client"
WIN_VM_SNET_CIDR="10.0.7.0/28"
WIN_VM_PRIV_IP="10.0.7.4/32"

## Windows Settings
WINDOWS_ADMIN_USER=$ADMIN_USERNAME

## Windows nodes settings
WINDOWS_NODE_POOL_NAME="npwin"
WINDOWS_NODE_POOL_NUMBER="1"



## Public IP name Windows
WIN_VM_PUBLIC_IP_NAME="rdcclientpublicip"
WIN_VM_DEFAULT_IP_CONFIG="ipconfig1"

## VM Windows Jump Server
WIN_RG_LOCATION=$LOCATION
WIN_VM_NAME="rdcclient-"$PURPOSE
WIN_VM_INTERNAL_NAME="rdcclient-"$PURPOSE
WIN_IMAGE_PROVIDER="MicrosoftWindowsServer"
WIN_IMAGE_OFFER="WindowsServer"
WIN_IMAGE_SKU="2019-Datacenter"
WIN_IMAGE_VERSION="latest"
WIN_IMAGE="$WIN_IMAGE_PROVIDER:$WIN_IMAGE_OFFER:$WIN_IMAGE_SKU:$WIN_IMAGE_VERSION"
WIN_PUBLIC_IP=""
WIN_VNET_NAME=$AKS_VNET
WIN_VNET_SUBNET_NAME="rdc-client"
#WIN_VM_SIZE="Standard_D2s_v3"
WIN_VM_SIZE="Standard_D4s_v3"
WIN_VM_STORAGE_SKU="Standard_LRS"
WIN_VM_OS_DISK_SIZE="130"
WIN_VM_OS_DISK_NAME="$WIN_VM_NAME""_disk_01"
WIN_VM_NSG_NAME="$WIN_VM_NAME""_nsg"
WIN_VM_NIC_NAME="$WIN_VM_NAME""nic01"
WIN_TAGS="env=kubernetes"



## Public IP name SSH
VM_PUBLIC_IP_NAME="sshclientpublicip"
VM_DEFAULT_IP_CONFIG="ipconfig1"

## VM SSH Client
RG_LOCATION=$LOCATION
AUTH_TYPE="ssh"
VM_NAME="sshclient-"$PURPOSE
VM_INTERNAL_NAME="sshclient-"$PURPOSE
IMAGE_PROVIDER="Canonical"
IMAGE_OFFER="UbuntuServer"
IMAGE_SKU="18.04-LTS"
IMAGE_VERSION="latest"
IMAGE="$IMAGE_PROVIDER:$IMAGE_OFFER:$IMAGE_SKU:$IMAGE_VERSION"
PUBLIC_IP="" 
VNET_NAME=$AKS_VNET
VNET_SUBNET_NAME="ssh-client"
VM_SIZE="Standard_D2s_v3"
#VM_SIZE="Standard_D4s_v3"
VM_STORAGE_SKU="Standard_LRS"
VM_OS_DISK_SIZE="40"
VM_OS_DISK_NAME="$VM_NAME""_disk_01"
VM_NSG_NAME="$VM_NAME""_nsg"
VM_NIC_NAME="$VM_NAME""nic01"
TAGS="env=kubernetes"

