## AKS Core Options
AKS_PURPOSE="win"
AKS_LOCATION="westeurope"
AKS_VERSION="1.22.11"
AKS_VNET_CIDR_PREFIX="10.5"
OS_SKU="Ubuntu"                            # CBLMariner, Ubuntu, Windows2019, Windows2022 or mariner
OS_WIN_SKU="Windows2019"

## AKS NP Instances Zones
AKS_SYS_NP_ZONES="1 2 3"                    # Define AKS Zones
AKS_USR_NP_ZONES="1 2 3"
AKS_WIN_NP_ZONES="1 2 3"

## Other Options
HAS_MANAGED_IDENTITY="1"
HAS_2ND_NODEPOOL="1"
HAS_JUMP_VMS="0"


AKS_RG_NAME="rg-aks-"$AKS_PURPOSE
AKS_CLUSTER_NAME="aks-"$AKS_PURPOSE
AKS_SYS_NODE_SIZE="Standard_D4s_v3"
AKS_USER_NODE_SIZE="Standard_D4s_v3"
AKS_SYS_NODE_COUNT="1"
AKS_USER_NODE_COUNT="1"
AKS_SYS_NODE_DISK_SIZE="90"
AKS_USER_NODE_DISK_SIZE="90"
AKS_WINDOWS_NODE_DISK_SIZE="90"
AKS_VM_SET_TYPE="VirtualMachineScaleSets" ## AvailabilitySet or VirtualMachineScaleSets
AKS_WINDOWS_NODE_POOL_NAME="npwin1"
AKS_WINDOWS_NODE_POOL_NUMBER="1"
AKS_SYS_NODE_POOL_NAME="sysnp01"
AKS_USER_NODE_POOL_NAME="usrnp01"

## Networking
AKS_VNET_RG=$AKS_RG_NAME
AKS_CNI_PLUGIN="azure"
AKS_VNET="vnet-"$AKS_CLUSTER_NAME
AKS_VNET_RG=$AKS_RG_NAME
AKS_VNET_CIDR="$AKS_VNET_CIDR_PREFIX.0.0/16"
AKS_SNET="snet-"$AKS_CLUSTER_NAME
AKS_SNET_CIDR="$AKS_VNET_CIDR_PREFIX.0.0/22"
AKS_CLUSTER_SRV_CIDR="$AKS_VNET_CIDR_PREFIX.4.0/23"
AKS_CLUSTER_DNS="$AKS_VNET_CIDR_PREFIX.4.10"
AKS_CLUSTER_DOCKER_BRIDGE="172.17.0.1/16"
SSH_VM_SNET_CIDR="$AKS_VNET_CIDR_PREFIX.6.0/28"
SSH_VM_PRIV_IP="$AKS_VNET_CIDR_PREFIX.6.4/32"
MY_HOME_PUBLIC_IP=$(curl ifconfig.io)
WIN_VM_SNET_CIDR="$AKS_VNET_CIDR_PREFIX.7.0/28"
WIN_VM_PRIV_IP="$AKS_VNET_CIDR_PREFIX.7.4/32"

## Public IP name Windows
WIN_VM_PUBLIC_IP_NAME="rdcclientpublicip"
WIN_VM_DEFAULT_IP_CONFIG="ipconfig1"

## VM Windows Jump Server
WIN_VM_RG_LOCATION=$AKS_LOCATION
WIN_VM_NAME="rdcclient-"$AKS_CLUSTER_NAME
WIN_VM_INTERNAL_NAME="clt-"$AKS_CLUSTER_NAME
WIN_VM_IMAGE_PROVIDER="MicrosoftWindowsServer"
WIN_VM_IMAGE_OFFER="WindowsServer"
WIN_VM_IMAGE_SKU="2019-Datacenter"
WIN_VM_IMAGE_VERSION="latest"
WIN_VM_IMAGE="$WIN_VM_IMAGE_PROVIDER:$WIN_VM_IMAGE_OFFER:$WIN_VM_IMAGE_SKU:$WIN_VM_IMAGE_VERSION"
WIN_VM_PUBLIC_IP=""
WIN_VM_VNET_NAME=$AKS_VNET
WIN_VM_VNET_SUBNET_NAME="rdc-client"
WIN_VM_SIZE="Standard_D4s_v3"
WIN_VM_STORAGE_SKU="Standard_LRS"
WIN_VM_OS_DISK_SIZE="130"
WIN_VM_OS_DISK_NAME="$WIN_VM_NAME""_disk_01"
WIN_VM_NSG_NAME="$WIN_VM_NAME""_nsg"
WIN_VM_NIC_NAME="$WIN_VM_NAME""nic01"
WIN_VM_TAGS="env=kubernetes"

## Public IP name SSH
SSH_VM_PUBLIC_IP_NAME="sshclientpublicip"
SSH_VM_DEFAULT_IP_CONFIG="ipconfig1"

## VM SSH Client
SSH_VM_RG_LOCATION=$AKS_LOCATION
SSH_VM_AUTH_TYPE="ssh"
SSH_VM_NAME="sshclient-"$AKS_PURPOSE
SSH_VM_INTERNAL_NAME="clt-"$AKS_PURPOSE
SSH_VM_IMAGE_PROVIDER="Canonical"
SSH_VM_IMAGE_OFFER="UbuntuServer"
SSH_VM_IMAGE_SKU="18.04-LTS"
SSH_VM_IMAGE_VERSION="latest"
SSH_VM_IMAGE="$SSH_VM_IMAGE_PROVIDER:$SSH_VM_IMAGE_OFFER:$SSH_VM_IMAGE_SKU:$SSH_VM_IMAGE_VERSION"
SSH_VM_PUBLIC_IP="" 
SSH_VM_VNET_NAME=$AKS_VNET
SSH_VM_VNET_SUBNET_NAME="snet-ssh-client"
SSH_VM_SIZE="Standard_D2s_v3"
SSH_VM_STORAGE_SKU="Standard_LRS"
SSH_VM_OS_DISK_SIZE="40"
SSH_VM_OS_DISK_NAME="$SSH_VM_NAME""_disk_01"
SSH_VM_NSG_NAME="$SSH_VM_NAME""_nsg"
SSH_VM_NIC_NAME="$SSH_VM_NAME""nic01"
SSH_VM_TAGS="env=kubernetes"
